-- GENERATED by tools/gen_mr_ui.py from Modding Files/source/resource_overhaul/flows.lua.
-- Edit the source or the generator, never this file.
DERPY_MR_FLOWS_DEFAULTS = {
    raid = 10,
    sack = 50,
    raze = 50,
    trade = 5,
    ai = true,
}
DERPY_MR_FLOWS_KIND = {
    raid = "raided",
    raze = "plundered",
    sack = "plundered",
    trade = "traded",
}
DERPY_MR_FLOWS_GOODS = {
    {stem = "salted_fish", res = "res_derpy_salted_fish"},
    {stem = "whale_oil", res = "res_derpy_whale_oil"},
    {stem = "sea_dragon_hide", res = "res_derpy_sea_dragon_hide"},
    {stem = "rum", res = "res_derpy_rum"},
    {stem = "amber", res = "res_derpy_amber"},
    {stem = "grain", res = "res_derpy_grain"},
    {stem = "warhorses", res = "res_derpy_warhorses"},
    {stem = "pipeweed", res = "res_derpy_pipeweed"},
    {stem = "books", res = "res_derpy_books"},
    {stem = "olive_oil", res = "res_derpy_olive_oil"},
    {stem = "silk", res = "res_derpy_silk"},
    {stem = "tea", res = "res_derpy_tea"},
    {stem = "jade", res = "res_derpy_jade"},
    {stem = "coal", res = "res_derpy_coal"},
    {stem = "silver", res = "res_derpy_silver"},
    {stem = "gromril", res = "res_derpy_gromril"},
    {stem = "quicksilver", res = "res_derpy_quicksilver"},
    {stem = "brimstone", res = "res_derpy_brimstone"},
    {stem = "brass", res = "res_derpy_brass"},
    {stem = "blackpowder", res = "res_derpy_blackpowder"},
    {stem = "ithilmar", res = "res_derpy_ithilmar"},
    {stem = "dragon_bone", res = "res_derpy_dragon_bone"},
    {stem = "lustrian_plumes", res = "res_derpy_lustrian_plumes"},
    {stem = "black_lotus", res = "res_derpy_black_lotus"},
    {stem = "incense", res = "res_derpy_incense"},
    {stem = "salted_meat", res = "res_derpy_salted_meat"},
    {stem = "carpets", res = "res_derpy_carpets"},
    {stem = "kvas", res = "res_derpy_kvas"},
    {stem = "rhinox_hides", res = "res_derpy_rhinox_hides"},
    {stem = "mead", res = "res_derpy_mead"},
    {stem = "glassware", res = "res_derpy_glassware"},
    {stem = "wool", res = "res_derpy_wool"},
    {stem = "porcelain", res = "res_derpy_porcelain"},
    {stem = "pearls", res = "res_derpy_pearls"},
    {stem = "starwood", res = "res_derpy_starwood"},
    {stem = "feathers", res = "res_derpy_feathers"},
    {stem = "wyvern_scales", res = "res_derpy_wyvern_scales"},
    {stem = "animals", res = "res_animals"},
    {stem = "dyes", res = "res_dyes"},
    {stem = "gems", res = "res_gems"},
    {stem = "gold_idols", res = "res_gold_idols"},
    {stem = "tusks", res = "res_ivory"},
    {stem = "medicine", res = "res_medicine"},
    {stem = "obsidian", res = "res_obsidian"},
    {stem = "furs", res = "res_rom_furs"},
    {stem = "beer", res = "res_rom_glass"},
    {stem = "iron", res = "res_rom_iron"},
    {stem = "salt", res = "res_rom_lead"},
    {stem = "marble", res = "res_rom_marble"},
    {stem = "pottery", res = "res_rom_textiles"},
    {stem = "timber", res = "res_rom_timber"},
    {stem = "wine", res = "res_rom_wine"},
    {stem = "spices", res = "res_spices"},
    {stem = "trinkets", res = "res_trinkets"},
}
-- Derpy Resource Overhaul: stores flows. Raids, sacks and razes carry stock out of a settlement's
-- stores into the taker's; trade agreements carry it between partners; a ledger and a 20-turn
-- history feed the Stores panel's chart.
-- Spec: docs/superpowers/specs/2026-10-02-resource-overhaul-stores-flows-design.md
--
-- THE SHIPPED FILE IS GENERATED. tools/gen_mr_ui.py puts DERPY_MR_FLOWS_DEFAULTS (the rates),
-- DERPY_MR_FLOWS_KIND (the factor each move books to) and DERPY_MR_FLOWS_GOODS (the 54 goods) in
-- front of this source. Edit this file, then run py tools/gen_mr_ui.py.
--
-- MULTIPLAYER: every change here happens inside a model event (turn start, occupation decision),
-- none from a click, so every machine runs the same moves.

DERPY_MR_FLOWS = DERPY_MR_FLOWS or {}
local F = DERPY_MR_FLOWS
local KIND = DERPY_MR_FLOWS_KIND

F.PREFIX = "derpy_mr_store_"
F.MCT = "derpy_more_resources"
F.RAIDING = "MILITARY_FORCE_ACTIVE_STANCE_TYPE_LAND_RAID"   -- CA's own test, wh2_twa03_rakarth.lua
F.DECISION = { occupation_decision_sack = "sack", occupation_decision_raze_without_occupy = "raze" }
F.state = F.state or { factions = {} }
F.cost = { raid = 0, turn = 0 }       -- seconds this round, for the in-game measurement only
F.SAVE = "derpy_mr_flows"
F.HISTORY = 20
-- WHICH PARTNERS LACK A GOOD (Task 1's measurement): "exists" asks the engine's
-- trade_resource_exists, "capital" asks whether the partner's capital store holds none.
F.LACK_TEST = "capital"

function F.say(msg)
    pcall(out, "[derpy_mr_flows] " .. tostring(msg))
end

-- AT LEAST 1 WHEN ANY IS HELD: floored alone, a store under 100/pct never loses anything.
function F.share(held, pct)
    if held <= 0 or pct <= 0 then return 0 end
    return math.max(1, math.floor(held * pct / 100))
end

function F.pool(region, stem)
    local ok, p = pcall(function()
        return region:pooled_resource_manager():resource(F.PREFIX .. stem)
    end)
    if ok and p and not p:is_null_interface() then return p end
    return nil
end

function F.held(region, stem)
    local p = F.pool(region, stem)
    if not p then return 0 end
    return p:value()
end

function F.free(region, stem)
    local p = F.pool(region, stem)
    if not p then return 0 end
    return math.max(0, p:maximum_value() - p:value())
end

-- ---- rates --------------------------------------------------------------------------------
-- FROZEN INTO THE SAVE the first time they are read, which is the first turn start. MCT's own
-- campaign gating is dead code (the Zharr Exchange's finding), so the save is the lock.
function F.mct(key)
    if not get_mct then return nil end
    local ok, v = pcall(function()
        local m = get_mct():get_mod_by_key(F.MCT)
        if not m then return nil end
        local o = m:get_option_by_key(key)
        if not o then return nil end
        return o:get_finalized_setting()
    end)
    if ok then return v end
    return nil
end

-- MULTIPLAYER TAKES THE DEFAULTS: two machines' MCT settings can differ and a move must not.
function F.read_rates()
    local mp = false
    pcall(function() mp = cm:is_multiplayer() end)
    local r = {}
    for k, d in pairs(DERPY_MR_FLOWS_DEFAULTS) do
        local v = nil
        if not mp then v = F.mct(k) end   -- NOT `not mp and F.mct(k) or nil`: an unticked box is false
        if type(v) ~= type(d) then v = d end
        if type(v) == "number" then v = math.floor(v + 0.5) end
        r[k] = v
    end
    return r
end

function F.rates()
    if not F.state.rates then F.state.rates = F.read_rates() end
    return F.state.rates
end

function F.is_human(fkey)
    if not fkey or fkey == "" then return false end
    local ok, h = pcall(function() return cm:get_faction(fkey):is_human() end)
    return ok and h == true
end

-- With "goods move between other factions" off, a move runs only with a player on one side.
function F.allowed(a, b)
    if F.rates().ai then return true end
    return F.is_human(a) or F.is_human(b)
end

-- ---- the ledger: human factions only, since only they see the panel ------------------------
function F.book(fkey)
    local b = F.state.factions[fkey]
    if not b then
        b = { turns = {}, total = {}, last = {}, now = {} }
        F.state.factions[fkey] = b
    end
    return b
end

function F.log(fkey, stem, field, n)
    if n <= 0 or not F.is_human(fkey) then return end
    local now = F.book(fkey).now
    now[stem] = now[stem] or {}
    now[stem][field] = (now[stem][field] or 0) + n
end

-- ---- moving stock ---------------------------------------------------------------------------
-- TWO TRANSACTIONS, NOT entity_transfer_pooled_resource: the receiver's share is clamped to its
-- free space here, so what does not fit is lost by rule (spec section 2) rather than by whatever
-- the engine does at the brim. The junction is two-way (gen_resource_overhaul.py FLOW_FACTORS),
-- so one id books both ends. `to` nil (a taker with no settlements) destroys the stock.
-- `from` nil is a source whose pools are already gone (a raze): nothing to book against it.
function F.move(from, to, stem, n, kind, from_key, to_key)
    if from then n = math.min(n, F.held(from, stem)) end
    if n <= 0 then return 0 end
    local j = F.PREFIX .. stem .. "_" .. kind
    if from then cm:entity_add_pooled_resource_transaction(from, j, -n) end
    local got = 0
    if to then
        got = math.min(n, F.free(to, stem))
        if got > 0 then cm:entity_add_pooled_resource_transaction(to, j, got) end
    end
    F.log(from_key, stem, kind .. "_out", n)
    F.log(to_key, stem, kind .. "_in", got)
    return got
end

-- The faction's settlement nearest (x, y); nil when it holds none.
function F.nearest(faction, x, y)
    local best, bd = nil, nil
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        local st = r:settlement()
        if not st:is_null_interface() then
            local dx, dy = st:logical_position_x() - x, st:logical_position_y() - y
            local d = dx * dx + dy * dy
            if bd == nil or d < bd then best, bd = r, d end
        end
    end
    return best
end

-- Every good in `region` with stock: pct of it to the taker's settlement nearest (x, y), the
-- taking army's position (plan deviation 3: the settlement may already be null at a raze).
-- `held` (stem -> n) is the battle's reading when the region's pools are gone.
function F.take(region, victim_key, taker, pct, kind, x, y, held)
    if pct <= 0 then return 0 end
    local to = F.nearest(taker, x, y)
    local from = not held and region or nil
    local taken = 0
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local n = F.share(held and held[g.stem] or F.held(region, g.stem), pct)
        if n > 0 then
            F.move(from, to, g.stem, n, kind, victim_key, taker:name())
            taken = taken + n
        end
    end
    return taken
end

-- The owner stock may be taken from, or nil: no region, no owner, a rebel, or the taker itself.
function F.victim(region, taker)
    if not region or region:is_null_interface() or region:is_abandoned() then return nil end
    local v = region:owning_faction()
    if v:is_null_interface() or v:is_rebel() or v:name() == taker:name() then return nil end
    return v
end

-- The raid this character makes: region, victim, taker; nil when it takes from nobody.
function F.raid_target(character)
    if not character:has_military_force() then return nil end
    if character:military_force():active_stance() ~= F.RAIDING then return nil end
    local taker = character:faction()
    local region = character:region()
    local v = F.victim(region, taker)
    if not v then return nil end      -- NO WAR TEST: CA pays raid gold from any owner's land
    if not F.allowed(taker:name(), v:name()) then return nil end
    return region, v, taker
end

function F.on_character_turn_start(character)
    local region, v, taker = F.raid_target(character)
    if not region then return end
    F.take(region, v:name(), taker, F.rates().raid, KIND.raid,
           character:logical_position_x(), character:logical_position_y())
end

-- WHAT F.take WOULD TAKE from `region` at `pct`: {total, parts = {{stem, n}}}, most first, or nil
-- when nothing. Read only - the plates' number, by the same F.share the move uses.
function F.preview(region, pct)
    local parts, total = {}, 0
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local n = F.share(F.held(region, g.stem), pct)
        if n > 0 then
            parts[#parts + 1] = { stem = g.stem, n = n }
            total = total + n
        end
    end
    if total == 0 then return nil end
    table.sort(parts, function(a, b)
        if a.n ~= b.n then return a.n > b.n end
        return a.stem < b.stem
    end)
    return { total = total, parts = parts }
end

-- WHAT THE RAID TAKES NEXT TURN, for the army's plate: F.preview plus `to`, the region key it
-- lands in (nil for a horde). Nothing before the rates are frozen: a UI read must not freeze
-- them on one machine ahead of the turn start that does it everywhere.
function F.raid_preview(character)
    local rates = F.state.rates
    if not rates or (rates.raid or 0) <= 0 then return nil end
    local region, _, taker = F.raid_target(character)
    if not region then return nil end
    local pv = F.preview(region, rates.raid)
    if not pv then return nil end
    local to = F.nearest(taker, character:logical_position_x(), character:logical_position_y())
    pv.to = to and to:name() or nil
    return pv
end

-- WHAT A SACK OR RAZE OF `region` WOULD TAKE, for the capture panel: F.preview plus `lost`, true
-- when the taker holds no settlement to carry it to. `kind` is "sack" or "raze"; nil otherwise,
-- and for the cases F.on_occupation skips (rebels, its own settlement).
function F.capture_preview(region, taker, kind)
    local rates = F.state.rates
    if not rates or (kind ~= "sack" and kind ~= "raze") or (rates[kind] or 0) <= 0 then return nil end
    if not F.victim(region, taker) then return nil end
    local pv = F.preview(region, rates[kind])
    if pv then pv.lost = taker:region_list():num_items() == 0 end
    return pv
end

function F.on_occupation(context)
    local what = F.DECISION[context:occupation_decision_type()]
    if not what then return end
    local character = context:character()
    local taker = character:faction()
    local victim = context:previous_owner()        -- empty for rebels
    if victim == nil or victim == "" or victim == taker:name() then return end
    if not F.allowed(taker:name(), victim) then return end
    local region = context:garrison_residence():region()
    local at_battle = F.at_battle[region:name()]
    F.at_battle[region:name()] = nil
    if F.pool(region, DERPY_MR_FLOWS_GOODS[1].stem) then
        at_battle = nil                            -- live stores win over the battle's reading
    elseif not at_battle then
        F.say("the stores of " .. region:name() .. " could not be read at the " .. what
              .. " - nothing taken")
        return
    end
    F.take(region, victim, taker, F.rates()[what], KIND[what],
           character:logical_position_x(), character:logical_position_y(), at_battle)
end

-- THE STORES AS THEY WERE AT THE BATTLE: the engine drops a razed region's pools before the
-- occupation decision fires (measured 2026-10-02, Venom Glade). CA's Bloodgrounds caches the
-- settlement the same way, on the same event. Not saved: the decision follows in the same session.
F.at_battle = {}
function F.on_battle(context)
    local pb = context:pending_battle()
    if not pb:has_contested_garrison() then return end
    local region = pb:contested_garrison():region()
    local t = {}
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local h = F.held(region, g.stem)
        if h > 0 then t[g.stem] = h end
    end
    F.at_battle[region:name()] = t
end

-- ---- trade --------------------------------------------------------------------------------
function F.capital(faction)
    if faction:has_home_region() then return faction:home_region() end
    local rl = faction:region_list()
    if rl:num_items() > 0 then return rl:item_at(0) end
    return nil
end

-- One pass over the exporter's settlements finds every good's fullest store, so the cost does
-- not grow with the number of partners.
function F.fullest(faction)
    local best = {}
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
            local h = F.held(r, g.stem)
            if h > 0 and (not best[g.stem] or h > best[g.stem].held) then
                best[g.stem] = { region = r, held = h }
            end
        end
    end
    return best
end

function F.lacks(partner, g)
    if F.LACK_TEST == "exists" then return not partner:trade_resource_exists(g.res) end
    local cap = F.capital(partner)
    return cap ~= nil and F.held(cap, g.stem) == 0
end

-- Each faction sends its own exports at its own turn start, so each direction of an agreement
-- runs once a round. A partner with no settlements gets nothing and nothing leaves.
function F.trade(exporter)
    local pct = F.rates().trade
    if pct <= 0 then return end
    local partners = exporter:factions_trading_with()
    if type(partners) == "boolean" then return end   -- measured 2026-10-02 for some faction
    local best = nil
    for i = 0, partners:num_items() - 1 do
        local partner = partners:item_at(i)
        local to = F.capital(partner)
        if to and F.allowed(exporter:name(), partner:name()) then
            best = best or F.fullest(exporter)
            for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
                local b = best[g.stem]
                if b and not F.stopped(exporter:name(), "export", g.stem)
                        and not F.stopped(partner:name(), "import", g.stem) and F.lacks(partner, g) then
                    -- ONLY WHAT FITS LEAVES: trade never destroys stock (spec section 3).
                    -- SURPLUS ONLY, NOT F.share's at-least-1: with it a raided single unit left
                    -- the same turn (measured 2026-10-02) and singles bounced between partners.
                    local n = math.min(math.floor(b.held * pct / 100), F.free(to, g.stem))
                    if n > 0 then
                        F.move(b.region, to, g.stem, n, KIND.trade, exporter:name(), partner:name())
                        b.held = b.held - n
                    end
                end
            end
        end
    end
end

-- ---- the player's trade switches (the Stores panel's Trade tab) ---------------------------
-- Saved in the faction's book as stop[dir][stem] = true; everything allowed by default.
-- Humans only: a computer-run faction has no panel to set them from.
F.DIRS = { export = true, import = true }
F.TAG = "dmr1"

function F.stopped(fkey, dir, stem)
    local b = F.state.factions[fkey]
    return b ~= nil and b.stop ~= nil and b.stop[dir] ~= nil and b.stop[dir][stem] == true
end

function F.toggle(fkey, dir, stem)
    if not F.DIRS[dir] or not F.is_human(fkey) then return end
    local known = false
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        if g.stem == stem then known = true end
    end
    if not known then return end
    local b = F.book(fkey)
    b.stop = b.stop or {}
    b.stop[dir] = b.stop[dir] or {}
    if F.stopped(fkey, dir, stem) then b.stop[dir][stem] = nil else b.stop[dir][stem] = true end
end

-- A CLICK NEVER WRITES THE MODEL ITSELF IN MULTIPLAYER: it goes out as a UITrigger, which CA
-- delivers to every machine in one order, and the listener toggles it everywhere at once.
function F.send(fkey, dir, stem)
    local mp = false
    pcall(function() mp = cm:is_multiplayer() end)
    if not mp then return F.toggle(fkey, dir, stem) end
    local f = cm:get_faction(fkey)
    if not f or f:is_null_interface() then return end
    CampaignUI.TriggerCampaignScriptEvent(f:command_queue_index(), F.TAG .. "|" .. dir .. "|" .. stem)
end

function F.on_ui_trigger(context)
    local dir, stem = string.match(context:trigger(), "^" .. F.TAG .. "|(%a+)|([%w_]+)$")
    if not dir then return end
    local cqi = context:faction_cqi()
    for _, k in ipairs(cm:get_human_factions()) do
        local f = cm:get_faction(k)
        if f and not f:is_null_interface() and f:command_queue_index() == cqi then
            F.toggle(k, dir, stem)
            local S = DERPY_MR_STORES
            if S and S.refresh then pcall(S.refresh) end
            return
        end
    end
end

-- ---- history ------------------------------------------------------------------------------
-- WHOLE NUMBERS ONLY: a fraction crosses CA's table save as "1,1" under a decimal-comma locale.
function F.push(b, turn, totals, made)
    b.turns[#b.turns + 1] = turn
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local t = b.total[g.stem] or {}
        b.total[g.stem] = t
        while #t < #b.turns - 1 do t[#t + 1] = 0 end      -- a good added by an update lines up
        t[#t + 1] = math.floor((totals[g.stem] or 0) + 0.5)
    end
    while #b.turns > F.HISTORY do
        table.remove(b.turns, 1)
        for _, t in pairs(b.total) do table.remove(t, 1) end
    end
    b.last = b.now
    for stem, m in pairs(made) do
        b.last[stem] = b.last[stem] or {}
        b.last[stem].made = math.floor(m + 0.5)
    end
    b.now = {}
end

-- At a human faction's turn start, after the engine has filled the stores.
function F.snapshot(faction)
    local S = DERPY_MR_STORES
    if not (S and S.read_realm) then return end
    local totals, made = {}, {}
    for _, s in ipairs(S.read_realm(faction)) do
        for stem, v in pairs(s.held) do totals[stem] = (totals[stem] or 0) + v end
        for stem, v in pairs(s.made) do made[stem] = (made[stem] or 0) + v end
    end
    F.push(F.book(faction:name()), cm:model():turn_number(), totals, made)
end

function F.series(fkey, stem)
    local b = F.state.factions and F.state.factions[fkey]
    if not b then return {}, {} end
    return b.turns, b.total[stem] or {}
end

function F.last(fkey, stem)
    local b = F.state.factions and F.state.factions[fkey]
    return (b and b.last[stem]) or {}
end

function F.on_faction_turn_start(faction)
    F.rates()                                     -- frozen at the first turn start
    if faction:is_human() then
        -- ITS OWN GUARD: the snapshot reads through the UI-side CCO and loc, and a throw there must
        -- not skip the trade below, which is model state every machine has to run alike
        F.guard(F.snapshot, faction)
        F.round_cost, F.cost = F.cost, { raid = 0, turn = 0 }
    end
    F.trade(faction)
end

function F.guard(fn, a, slot)
    local t0 = os.clock()
    local ok, e = pcall(fn, a)
    if slot then F.cost[slot] = (F.cost[slot] or 0) + os.clock() - t0 end
    if not ok then F.say(e) end
end

function F.init()
    if F.started then return end
    F.started = true
    core:add_listener("derpy_mr_flows_raid", "CharacterTurnStart", true,
        function(context) F.guard(F.on_character_turn_start, context:character(), "raid") end, true)
    core:add_listener("derpy_mr_flows_occupation", "CharacterPerformsSettlementOccupationDecision", true,
        function(context) F.guard(F.on_occupation, context) end, true)
    core:add_listener("derpy_mr_flows_battle", "CharacterCompletedBattle", true,
        function(context) F.guard(F.on_battle, context) end, true)
    core:add_listener("derpy_mr_flows_ui", "UITrigger", true,
        function(context) F.guard(F.on_ui_trigger, context) end, true)
    core:add_listener("derpy_mr_flows_turn", "FactionTurnStart", true,
        function(context) F.guard(F.on_faction_turn_start, context:faction(), "turn") end, true)
end

cm:add_first_tick_callback(function() F.init() end)

-- FIRST IN CA'S LISTS, NOT APPENDED: cm:saving_game and cm:loading_game call every mod's
-- callback in one unprotected loop, so a mod that throws ahead of this one would stop it and the
-- save would go out without the history (the Zharr Exchange's 2026-10-02 lesson).
local function first(kind, fn)
    local list = cm[kind .. "_game_callbacks"]
    if type(list) == "table" then
        table.insert(list, 1, fn)
    elseif kind == "saving" then
        cm:add_saving_game_callback(fn)
    else
        cm:add_loading_game_callback(fn)
    end
end

first("loading", function(context)
    local ok, t = pcall(function() return cm:load_named_value(F.SAVE, {}, context) end)
    if ok and type(t) == "table" then
        F.state = t
    else
        F.state = {}
        F.say("could not load the stores history: " .. tostring(t))
    end
    F.state.factions = F.state.factions or {}
end)

first("saving", function(context)
    local ok, e = pcall(function() cm:save_named_value(F.SAVE, F.state, context) end)
    if not ok then F.say("could not save the stores history: " .. tostring(e)) end
end)
