-- Derpy Resource Overhaul: the AI builds the rare goods' buildings, only where they work.
-- GENERATED by tools/gen_resource_overhaul.py (ai_script). Edit the generator, not this file.
MR_AI = {}
MR_AI.PACE = 5
MR_AI.RESERVE = 2
MR_AI.COST = { 1000, 2000, 3000 }
MR_AI.REQ = { 1, 2, 3 }   -- the settlement tier each level needs
MR_AI.GOODS = { "black_lotus", "dragon_bone", "feathers", "gromril", "ithilmar", "sea_dragon_hide", "starwood", "wyvern_scales" }
MR_AI.CHAIN = {
    black_lotus = { wh2_main_def_dark_elves = "derpy_mr_bld_black_lotus_def", wh2_main_skv_skaven = "derpy_mr_bld_black_lotus_skv" },
    dragon_bone = { wh_main_brt_bretonnia = "derpy_mr_bld_dragon_bone_brt", wh3_dlc23_chd_chaos_dwarfs = "derpy_mr_bld_dragon_bone_chd", wh_main_chs_chaos = "derpy_mr_bld_dragon_bone_chs", wh2_dlc11_cst_vampire_coast = "derpy_mr_bld_dragon_bone_cst", wh3_main_cth_cathay = "derpy_mr_bld_dragon_bone_cth", wh2_main_def_dark_elves = "derpy_mr_bld_dragon_bone_def", wh_main_dwf_dwarfs = "derpy_mr_bld_dragon_bone_dwf", wh_main_emp_empire = "derpy_mr_bld_dragon_bone_emp", wh_main_grn_greenskins = "derpy_mr_bld_dragon_bone_grn", wh2_main_hef_high_elves = "derpy_mr_bld_dragon_bone_hef", wh3_main_ksl_kislev = "derpy_mr_bld_dragon_bone_ksl", wh2_main_lzd_lizardmen = "derpy_mr_bld_dragon_bone_lzd", wh_dlc08_nor_norsca = "derpy_mr_bld_dragon_bone_nor", wh3_main_ogr_ogre_kingdoms = "derpy_mr_bld_dragon_bone_ogr", wh2_main_skv_skaven = "derpy_mr_bld_dragon_bone_skv", wh_main_vmp_vampire_counts = "derpy_mr_bld_dragon_bone_vmp", wh_dlc05_wef_wood_elves = "derpy_mr_bld_dragon_bone_wef" },
    feathers = { wh_main_brt_bretonnia = "derpy_mr_bld_feathers_brt", wh_main_emp_empire = "derpy_mr_bld_feathers_emp" },
    gromril = { wh_main_dwf_dwarfs = "derpy_mr_bld_gromril" },
    ithilmar = { wh2_main_hef_high_elves = "derpy_mr_bld_ithilmar" },
    sea_dragon_hide = { wh2_main_def_dark_elves = "derpy_mr_bld_sea_dragon_hide" },
    starwood = { wh_dlc05_wef_wood_elves = "derpy_mr_bld_starwood" },
    wyvern_scales = { wh_main_grn_greenskins = "derpy_mr_bld_wyvern_scales_grn", wh3_main_ogr_ogre_kingdoms = "derpy_mr_bld_wyvern_scales_ogr" },
}
MR_AI.REGIONS = {
    black_lotus = {
        ["cr_combi_region_caves_of_eystri_obygdir"] = true,
        ["cr_combi_region_hewn"] = true,
        ["cr_combi_region_leilou"] = true,
        ["cr_combi_region_long_vi"] = true,
        ["cr_combi_region_mata_mire"] = true,
        ["cr_combi_region_morakot"] = true,
        ["cr_combi_region_nagara_ishsva"] = true,
        ["cr_combi_region_naknakorn"] = true,
        ["cr_combi_region_phenom"] = true,
        ["cr_combi_region_preyveer"] = true,
        ["cr_combi_region_rekan"] = true,
        ["cr_combi_region_sanctuary_of_lies"] = true,
        ["cr_combi_region_sangirun"] = true,
        ["cr_combi_region_sanmal"] = true,
        ["cr_combi_region_sinsay"] = true,
        ["cr_combi_region_sipsaat"] = true,
        ["cr_combi_region_soglap"] = true,
        ["cr_combi_region_souphanousiphon"] = true,
        ["cr_combi_region_tambang"] = true,
        ["cr_oldworld_region_cape_kharpentharia"] = true,
        ["cr_oldworld_region_mangrove_port"] = true,
        ["cr_oldworld_region_soteks_trail"] = true,
        ["cr_oldworld_region_village_of_the_leopard_skins"] = true,
        ["wh3_main_combi_region_cuexotl"] = true,
        ["wh3_main_combi_region_teotiqua"] = true,
        ["wh3_main_combi_region_the_golden_tower"] = true,
    },
    dragon_bone = {
        ["cr_oldworld_region_darkhold"] = true,
        ["cr_oldworld_region_dragon_fang_mount"] = true,
        ["cr_oldworld_region_dragonhorn_mines"] = true,
        ["cr_oldworld_region_dragons_death"] = true,
        ["cr_oldworld_region_the_bone_gulch"] = true,
        ["wh3_main_chaos_region_darkhold"] = true,
        ["wh3_main_chaos_region_dragon_fang_mount"] = true,
        ["wh3_main_combi_region_dragon_fang_mount"] = true,
        ["wh3_main_combi_region_dragonhorn_mines"] = true,
        ["wh3_main_combi_region_the_bone_gulch"] = true,
        ["wh3_main_combi_region_vauls_anvil_ulthuan"] = true,
    },
    feathers = {
        ["cr_oldworld_region_alimento"] = true,
        ["cr_oldworld_region_barak_varr"] = true,
        ["cr_oldworld_region_bilious_basilica"] = true,
        ["cr_oldworld_region_brass_keep"] = true,
        ["cr_oldworld_region_castle_sanglac"] = true,
        ["cr_oldworld_region_caverns_of_unyielding_shadow"] = true,
        ["cr_oldworld_region_durango"] = true,
        ["cr_oldworld_region_karaz_ghumzul"] = true,
        ["cr_oldworld_region_llaqueno"] = true,
        ["cr_oldworld_region_montenas"] = true,
        ["cr_oldworld_region_mount_zardele"] = true,
        ["cr_oldworld_region_queekwell"] = true,
        ["cr_oldworld_region_reas"] = true,
        ["cr_oldworld_region_siernos"] = true,
        ["cr_oldworld_region_turin"] = true,
        ["cr_oldworld_region_valley_of_windmills"] = true,
        ["wh3_main_chaos_region_brass_keep"] = true,
        ["wh3_main_combi_region_blackstone_post"] = true,
        ["wh3_main_combi_region_brass_keep"] = true,
        ["wh3_main_combi_region_massif_orcal"] = true,
        ["wh3_main_combi_region_the_black_pit"] = true,
    },
    gromril = {
        ["cr_oldworld_region_bloody_spires"] = true,
        ["cr_oldworld_region_grimhold"] = true,
        ["cr_oldworld_region_karag_ziflin"] = true,
        ["cr_oldworld_region_karak_azorn"] = true,
        ["cr_oldworld_region_karak_vrag"] = true,
        ["cr_oldworld_region_kazad_dumund"] = true,
        ["cr_oldworld_region_kazad_urkbavak"] = true,
        ["cr_oldworld_region_khazid_bordkarag"] = true,
        ["cr_oldworld_region_khazid_nekewukaz"] = true,
        ["cr_oldworld_region_kraka_drak"] = true,
        ["cr_oldworld_region_kraka_ornsmotek"] = true,
        ["cr_oldworld_region_lost_archway_of_valaya"] = true,
        ["cr_oldworld_region_stormvrack_mount"] = true,
        ["wh3_main_chaos_region_kraka_drak"] = true,
        ["wh3_main_chaos_region_mount_gunbad"] = true,
        ["wh3_main_combi_region_black_crag"] = true,
        ["wh3_main_combi_region_karak_azgal"] = true,
        ["wh3_main_combi_region_karak_hirn"] = true,
        ["wh3_main_combi_region_karak_ungor"] = true,
        ["wh3_main_combi_region_karak_vrag"] = true,
        ["wh3_main_combi_region_karak_zorn"] = true,
        ["wh3_main_combi_region_karaz_a_karak"] = true,
        ["wh3_main_combi_region_kraka_drak"] = true,
        ["wh3_main_combi_region_mine_of_the_bearded_skulls"] = true,
        ["wh3_main_combi_region_mount_gunbad"] = true,
        ["wh3_main_combi_region_zhufbar"] = true,
    },
    ithilmar = {
        ["wh3_main_combi_region_tor_anlec"] = true,
        ["wh3_main_combi_region_tor_anroc"] = true,
        ["wh3_main_combi_region_vauls_anvil_ulthuan"] = true,
    },
    sea_dragon_hide = {
        ["wh3_main_combi_region_arnheim"] = true,
        ["wh3_main_combi_region_fortress_of_the_damned"] = true,
        ["wh3_main_combi_region_hag_graef"] = true,
        ["wh3_main_combi_region_karond_kar"] = true,
        ["wh3_main_combi_region_naggarond"] = true,
        ["wh3_main_combi_region_the_twisted_glade"] = true,
    },
    starwood = {
        ["cr_oldworld_region_crag_halls_of_findol"] = true,
        ["cr_oldworld_region_feast_halls_of_the_wardancers"] = true,
        ["cr_oldworld_region_glade_of_eternal_midnight"] = true,
        ["cr_oldworld_region_glade_of_eternal_moonlight"] = true,
        ["cr_oldworld_region_halls_of_anaereth"] = true,
        ["cr_oldworld_region_halls_of_equos"] = true,
        ["cr_oldworld_region_kings_glade"] = true,
        ["cr_oldworld_region_tal_amere"] = true,
        ["cr_oldworld_region_tal_esth"] = true,
        ["cr_oldworld_region_the_oak_of_ages"] = true,
        ["cr_oldworld_region_tyr_vanna"] = true,
        ["cr_oldworld_region_vauls_anvil"] = true,
        ["cr_oldworld_region_waterfall_palace"] = true,
        ["wh3_main_combi_region_crag_halls_of_findol"] = true,
        ["wh3_main_combi_region_kings_glade"] = true,
        ["wh3_main_combi_region_the_oak_of_ages"] = true,
        ["wh3_main_combi_region_vauls_anvil_loren"] = true,
        ["wh3_main_combi_region_waterfall_palace"] = true,
    },
    wyvern_scales = {
        ["cr_combi_region_caves_of_fire"] = true,
        ["cr_combi_region_eye_of_the_tiger"] = true,
        ["cr_combi_region_himaranya"] = true,
        ["cr_combi_region_nandakshi"] = true,
        ["cr_combi_region_shantivara"] = true,
        ["cr_combi_region_temple_of_shear_khawn"] = true,
        ["cr_combi_region_vajrapur"] = true,
        ["cr_oldworld_region_angry_fist_camp"] = true,
        ["cr_oldworld_region_another_golgfag_monument"] = true,
        ["cr_oldworld_region_black_fang"] = true,
        ["cr_oldworld_region_blackclaw_lair"] = true,
        ["cr_oldworld_region_blizzardpeak"] = true,
        ["cr_oldworld_region_blood_river"] = true,
        ["cr_oldworld_region_bloodmaw_camp"] = true,
        ["cr_oldworld_region_boulderclubs_camp"] = true,
        ["cr_oldworld_region_bulgers_camp"] = true,
        ["cr_oldworld_region_carrion_craggs"] = true,
        ["cr_oldworld_region_circle_of_the_sun"] = true,
        ["cr_oldworld_region_crossed_clubs_camp"] = true,
        ["cr_oldworld_region_cursed_mount"] = true,
        ["cr_oldworld_region_ekrund"] = true,
        ["cr_oldworld_region_fleshgreeders_camp"] = true,
        ["cr_oldworld_region_floating_mountain"] = true,
        ["cr_oldworld_region_fulg_camp"] = true,
        ["cr_oldworld_region_golgfags_monument"] = true,
        ["cr_oldworld_region_gorger_rock"] = true,
        ["cr_oldworld_region_granitetooth_graveyard"] = true,
        ["cr_oldworld_region_grimmpeak"] = true,
        ["cr_oldworld_region_gul_grogs_monolith"] = true,
        ["cr_oldworld_region_hidden_hoard_of_hrak_opaleye"] = true,
        ["cr_oldworld_region_horroks_gap"] = true,
        ["cr_oldworld_region_ice_caverns_of_ymirdrak"] = true,
        ["cr_oldworld_region_icespewer"] = true,
        ["cr_oldworld_region_ironskin_camp"] = true,
        ["cr_oldworld_region_karak_azorn"] = true,
        ["cr_oldworld_region_karak_vrag"] = true,
        ["cr_oldworld_region_komar"] = true,
        ["cr_oldworld_region_loose_tooth_camp"] = true,
        ["cr_oldworld_region_mount_cragg"] = true,
        ["cr_oldworld_region_quests_end"] = true,
        ["cr_oldworld_region_rockskulls_camp"] = true,
        ["cr_oldworld_region_sabre_mountain"] = true,
        ["cr_oldworld_region_sabreskin_camp"] = true,
        ["cr_oldworld_region_slavetakers_camp"] = true,
        ["cr_oldworld_region_the_great_hunt"] = true,
        ["cr_oldworld_region_the_horn"] = true,
        ["cr_oldworld_region_thunderhoof_camp"] = true,
        ["wh3_main_combi_region_amblepeak"] = true,
        ["wh3_main_combi_region_bloodpeak"] = true,
        ["wh3_main_combi_region_deff_gorge"] = true,
        ["wh3_main_combi_region_fire_mouth"] = true,
        ["wh3_main_combi_region_gorger_rock"] = true,
        ["wh3_main_combi_region_grimtop"] = true,
        ["wh3_main_combi_region_karak_krakaten"] = true,
        ["wh3_main_combi_region_karak_vrag"] = true,
        ["wh3_main_combi_region_sabre_mountain"] = true,
        ["wh3_main_combi_region_the_maw_gate"] = true,
        ["wh3_main_combi_region_titans_notch"] = true,
        ["wh3_main_combi_region_vale_of_titans"] = true,
        ["wh3_main_combi_region_valley_of_horns"] = true,
        ["wh3_main_combi_region_yhetee_peak"] = true,
    },
}

local function say(s) if out then out("derpy_mr_ai: " .. s) end end

-- Bounded, so float32 keeps it exact (the Exchange's EX.key_hash).
function MR_AI.hash(s)
    local h = 0
    for i = 1, #s do h = (h * 31 + string.byte(s, i)) % 65536 end
    return h
end

function MR_AI.due(fname, turn)
    return (turn + MR_AI.hash(fname)) % MR_AI.PACE == 0
end

-- "<chain>_<n>" -> n, by prefix, no pattern: chain keys are plain and a pattern match would read
-- "black_lotus" as the start of "black_lotus_def".
function MR_AI.level_in(chain, bname)
    local pre = chain .. "_"
    if string.sub(bname, 1, #pre) ~= pre then return nil end
    return tonumber(string.sub(bname, #pre + 1))
end

function MR_AI.tier(region)
    local ok, t = pcall(function()
        return region:settlement():primary_slot():building():building_level()
    end)
    return ok and t or 0
end

-- The slot holding this chain in the region, and its level.
function MR_AI.find(region, chain)
    local slots = region:slot_list()
    for i = 0, slots:num_items() - 1 do
        local s = slots:item_at(i)
        if s:has_building() then
            local n = MR_AI.level_in(chain, s:building():name())
            if n then return s, n end
        end
    end
    return nil, nil
end

-- What this faction may build: {good, chain, region} for every owned lore region.
function MR_AI.options(faction)
    local out_, culture = {}, faction:culture()
    local regions = faction:region_list()
    for _, good in ipairs(MR_AI.GOODS) do
        local chain = (MR_AI.CHAIN[good] or {})[culture]
        if chain then
            for i = 0, regions:num_items() - 1 do
                local r = regions:item_at(i)
                if MR_AI.REGIONS[good][r:name()] then out_[#out_ + 1] = { good, chain, r } end
            end
        end
    end
    return out_
end

-- ONE ACTION, OR NONE. An upgrade first - a building the faction already owns, whose next level
-- the settlement's tier allows - then a new building. Returns what it did, for the log and the
-- harness.
function MR_AI.act(faction)
    local fname = faction:name()
    local opts = MR_AI.options(faction)
    if #opts == 0 then return nil end
    local function afford(cost) return faction:treasury() >= cost * MR_AI.RESERVE end
    for _, o in ipairs(opts) do
        local slot, n = MR_AI.find(o[3], o[2])
        if slot and n < 3 and MR_AI.tier(o[3]) >= MR_AI.REQ[n + 1] and afford(MR_AI.COST[n + 1]) then
            local want = o[2] .. "_" .. (n + 1)
            cm:instantly_upgrade_building_in_region(slot, want)
            local got = MR_AI.find(o[3], o[2])
            if got and got:building():name() == want then
                cm:treasury_mod(fname, -MR_AI.COST[n + 1])
                say(fname .. " upgraded " .. want .. " in " .. o[3]:name())
                return "upgrade " .. want .. " " .. o[3]:name()
            end
            say(fname .. " could not upgrade to " .. want .. " in " .. o[3]:name())
        end
    end
    for _, o in ipairs(opts) do
        if not MR_AI.find(o[3], o[2]) and MR_AI.tier(o[3]) >= MR_AI.REQ[1] and afford(MR_AI.COST[1]) then
            local want = o[2] .. "_1"
            cm:add_building_to_settlement(o[3]:name(), want)
            if MR_AI.find(o[3], o[2]) then
                cm:treasury_mod(fname, -MR_AI.COST[1])
                say(fname .. " built " .. want .. " in " .. o[3]:name())
                return "build " .. want .. " " .. o[3]:name()
            end
            -- no free slot that takes it: try the next region, and say so once in the log
            say(fname .. " found no slot for " .. want .. " in " .. o[3]:name())
        end
    end
    return nil
end

function MR_AI.turn(faction)
    if faction:is_human() or faction:is_dead() then return nil end
    if not MR_AI.due(faction:name(), cm:model():turn_number()) then return nil end
    local ok, did = pcall(MR_AI.act, faction)
    if not ok then say("error for " .. faction:name() .. ": " .. tostring(did)) return nil end
    return did
end

if core then
    core:add_listener("derpy_mr_ai", "FactionTurnStart", true,
        function(context) MR_AI.turn(context:faction()) end, true)
end
