-- GENERATED by tools/gen_mr_ui.py from Modding Files/source/resource_overhaul/flows.lua.
-- Edit the source or the generator, never this file.
DERPY_MR_FLOWS_DEFAULTS = {
    raid = 10,
    sack = 50,
    raze = 50,
    trade = 5,
    ai = true,
    upkeep = true,
    actions = true,
}
DERPY_MR_FLOWS_KIND = {
    eat = "eaten",
    move = "moved",
    raid = "raided",
    raze = "plundered",
    sack = "plundered",
    sell = "sold",
    spend = "spent",
    trade = "traded",
}
DERPY_MR_FLOWS_GOODS = {
    {stem = "salted_fish", res = "res_derpy_salted_fish", use = "provisions"},
    {stem = "whale_oil", res = "res_derpy_whale_oil", use = "war"},
    {stem = "sea_dragon_hide", res = "res_derpy_sea_dragon_hide", use = "mounts"},
    {stem = "rum", res = "res_derpy_rum", use = "provisions"},
    {stem = "amber", res = "res_derpy_amber", use = "luxuries"},
    {stem = "grain", res = "res_derpy_grain", use = "provisions"},
    {stem = "warhorses", res = "res_derpy_warhorses", use = "mounts"},
    {stem = "pipeweed", res = "res_derpy_pipeweed", use = "luxuries"},
    {stem = "books", res = "res_derpy_books", use = "luxuries"},
    {stem = "olive_oil", res = "res_derpy_olive_oil", use = "provisions"},
    {stem = "silk", res = "res_derpy_silk", use = "luxuries"},
    {stem = "tea", res = "res_derpy_tea", use = "provisions"},
    {stem = "jade", res = "res_derpy_jade", use = "luxuries"},
    {stem = "coal", res = "res_derpy_coal", use = "war"},
    {stem = "silver", res = "res_derpy_silver", use = "luxuries"},
    {stem = "gromril", res = "res_derpy_gromril", use = "war"},
    {stem = "quicksilver", res = "res_derpy_quicksilver", use = "war"},
    {stem = "brimstone", res = "res_derpy_brimstone", use = "war"},
    {stem = "brass", res = "res_derpy_brass", use = "war"},
    {stem = "blackpowder", res = "res_derpy_blackpowder", use = "war"},
    {stem = "ithilmar", res = "res_derpy_ithilmar", use = "war"},
    {stem = "dragon_bone", res = "res_derpy_dragon_bone", use = "mounts"},
    {stem = "lustrian_plumes", res = "res_derpy_lustrian_plumes", use = "luxuries"},
    {stem = "black_lotus", res = "res_derpy_black_lotus", use = "luxuries"},
    {stem = "incense", res = "res_derpy_incense", use = "luxuries"},
    {stem = "salted_meat", res = "res_derpy_salted_meat", use = "provisions"},
    {stem = "carpets", res = "res_derpy_carpets", use = "luxuries"},
    {stem = "kvas", res = "res_derpy_kvas", use = "provisions"},
    {stem = "rhinox_hides", res = "res_derpy_rhinox_hides", use = "mounts"},
    {stem = "mead", res = "res_derpy_mead", use = "provisions"},
    {stem = "glassware", res = "res_derpy_glassware", use = "building"},
    {stem = "wool", res = "res_derpy_wool", use = "luxuries"},
    {stem = "porcelain", res = "res_derpy_porcelain", use = "luxuries"},
    {stem = "pearls", res = "res_derpy_pearls", use = "luxuries"},
    {stem = "starwood", res = "res_derpy_starwood", use = "building"},
    {stem = "feathers", res = "res_derpy_feathers", use = "mounts"},
    {stem = "wyvern_scales", res = "res_derpy_wyvern_scales", use = "mounts"},
    {stem = "animals", res = "res_animals", use = "mounts"},
    {stem = "dyes", res = "res_dyes", use = "luxuries"},
    {stem = "gems", res = "res_gems", use = "luxuries"},
    {stem = "gold_idols", res = "res_gold_idols", use = "luxuries"},
    {stem = "tusks", res = "res_ivory", use = "mounts"},
    {stem = "medicine", res = "res_medicine", use = "provisions"},
    {stem = "obsidian", res = "res_obsidian", use = "war"},
    {stem = "furs", res = "res_rom_furs", use = "mounts"},
    {stem = "beer", res = "res_rom_glass", use = "provisions"},
    {stem = "iron", res = "res_rom_iron", use = "war"},
    {stem = "salt", res = "res_rom_lead", use = "provisions"},
    {stem = "marble", res = "res_rom_marble", use = "building"},
    {stem = "pottery", res = "res_rom_textiles", use = "building"},
    {stem = "timber", res = "res_rom_timber", use = "building"},
    {stem = "wine", res = "res_rom_wine", use = "provisions"},
    {stem = "spices", res = "res_spices", use = "provisions"},
    {stem = "trinkets", res = "res_trinkets", use = "luxuries"},
}
DERPY_MR_FLOWS_ORDERS = {
    festival = {use = "luxuries", bundle = "derpy_mr_order_festival"},
    muster = {use = "war", bundle = "derpy_mr_order_muster"},
    great_works = {use = "building", bundle = "derpy_mr_order_great_works"},
}
DERPY_MR_FLOWS_ORDER = {200, 5, 10}   -- cost, turns, cooldown
DERPY_MR_FLOWS_SELL_RATE = {building = 2, luxuries = 5, mounts = 4, provisions = 1, war = 3}
DERPY_MR_FLOWS_NO_STORES = {"dae", "kho", "nur", "sla", "tze", "tmb", "nag", "bst"}
DERPY_MR_FLOWS_BUNDLES = {
    provisions = "derpy_mr_well_fed",
    war = "derpy_mr_garrison_stocked",
    luxuries = "derpy_mr_comforts",
}
-- Derpy Resource Overhaul: stores flows. Raids, sacks and razes carry stock out of a settlement's
-- stores into the taker's; trade agreements carry it between partners; a ledger and a 20-turn
-- history feed the Stores panel's chart.
-- Spec: docs/superpowers/specs/2026-10-02-resource-overhaul-stores-flows-design.md
--
-- THE SHIPPED FILE IS GENERATED. tools/gen_mr_ui.py puts DERPY_MR_FLOWS_DEFAULTS (the rates),
-- DERPY_MR_FLOWS_KIND (the factor each move books to) and DERPY_MR_FLOWS_GOODS (the 54 goods) in
-- front of this source. Edit this file, then run py tools/gen_mr_ui.py.
--
-- MULTIPLAYER: every change here happens inside a model event (turn start, occupation decision),
-- none from a click, so every machine runs the same moves.

DERPY_MR_FLOWS = DERPY_MR_FLOWS or {}
local F = DERPY_MR_FLOWS
local KIND = DERPY_MR_FLOWS_KIND

F.PREFIX = "derpy_mr_store_"
F.MCT = "derpy_more_resources"
F.RAIDING = "MILITARY_FORCE_ACTIVE_STANCE_TYPE_LAND_RAID"   -- CA's own test, wh2_twa03_rakarth.lua
F.DECISION = { occupation_decision_sack = "sack", occupation_decision_raze_without_occupy = "raze" }
F.state = F.state or { factions = {} }
F.cost = { raid = 0, turn = 0 }       -- seconds this round, for the in-game measurement only
F.SAVE = "derpy_mr_flows"
F.HISTORY = 20
-- WHICH PARTNERS LACK A GOOD (Task 1's measurement): "exists" asks the engine's
-- trade_resource_exists, "capital" asks whether the partner's capital store holds none.
F.LACK_TEST = "capital"

function F.say(msg)
    pcall(out, "[derpy_mr_flows] " .. tostring(msg))
end

-- AT LEAST 1 WHEN ANY IS HELD: floored alone, a store under 100/pct never loses anything.
function F.share(held, pct)
    if held <= 0 or pct <= 0 then return 0 end
    return math.max(1, math.floor(held * pct / 100))
end

function F.pool(region, stem)
    local ok, p = pcall(function()
        return region:pooled_resource_manager():resource(F.PREFIX .. stem)
    end)
    if ok and p and not p:is_null_interface() then return p end
    return nil
end

function F.held(region, stem)
    local p = F.pool(region, stem)
    if not p then return 0 end
    return p:value()
end

function F.free(region, stem)
    local p = F.pool(region, stem)
    if not p then return 0 end
    return math.max(0, p:maximum_value() - p:value())
end

-- ---- rates --------------------------------------------------------------------------------
-- FROZEN INTO THE SAVE the first time they are read, which is the first turn start. MCT's own
-- campaign gating is dead code (the Zharr Exchange's finding), so the save is the lock.
function F.mct(key)
    if not get_mct then return nil end
    local ok, v = pcall(function()
        local m = get_mct():get_mod_by_key(F.MCT)
        if not m then return nil end
        local o = m:get_option_by_key(key)
        if not o then return nil end
        return o:get_finalized_setting()
    end)
    if ok then return v end
    return nil
end

-- MULTIPLAYER TAKES THE DEFAULTS: two machines' MCT settings can differ and a move must not.
function F.read_rates()
    local mp = false
    pcall(function() mp = cm:is_multiplayer() end)
    local r = {}
    for k, d in pairs(DERPY_MR_FLOWS_DEFAULTS) do
        local v = nil
        if not mp then v = F.mct(k) end   -- NOT `not mp and F.mct(k) or nil`: an unticked box is false
        if type(v) ~= type(d) then v = d end
        if type(v) == "number" then v = math.floor(v + 0.5) end
        r[k] = v
    end
    return r
end

function F.rates()
    if not F.state.rates then F.state.rates = F.read_rates() end
    return F.state.rates
end

function F.is_human(fkey)
    if not fkey or fkey == "" then return false end
    local ok, h = pcall(function() return cm:get_faction(fkey):is_human() end)
    return ok and h == true
end

-- With "goods move between other factions" off, a move runs only with a player on one side.
function F.allowed(a, b)
    if F.rates().ai then return true end
    return F.is_human(a) or F.is_human(b)
end

-- ---- the ledger: human factions only, since only they see the panel ------------------------
function F.book(fkey)
    local b = F.state.factions[fkey]
    if not b then
        b = { turns = {}, total = {}, last = {}, now = {} }
        F.state.factions[fkey] = b
    end
    return b
end

function F.log(fkey, stem, field, n)
    if n <= 0 or not F.is_human(fkey) then return end
    local now = F.book(fkey).now
    now[stem] = now[stem] or {}
    now[stem][field] = (now[stem][field] or 0) + n
end

-- ---- moving stock ---------------------------------------------------------------------------
-- TWO TRANSACTIONS, NOT entity_transfer_pooled_resource: the receiver's share is clamped to its
-- free space here, so what does not fit is lost by rule (spec section 2) rather than by whatever
-- the engine does at the brim. The junction is two-way (gen_resource_overhaul.py FLOW_FACTORS),
-- so one id books both ends. `to` nil (a taker with no settlements) destroys the stock.
-- `from` nil is a source whose pools are already gone (a raze): nothing to book against it.
function F.move(from, to, stem, n, kind, from_key, to_key)
    if from then n = math.min(n, F.held(from, stem)) end
    if n <= 0 then return 0 end
    local j = F.PREFIX .. stem .. "_" .. kind
    if from then cm:entity_add_pooled_resource_transaction(from, j, -n) end
    local got = 0
    if to then
        got = math.min(n, F.free(to, stem))
        if got > 0 then cm:entity_add_pooled_resource_transaction(to, j, got) end
    end
    F.log(from_key, stem, kind .. "_out", n)
    F.log(to_key, stem, kind .. "_in", got)
    return got
end

-- The faction's settlement nearest (x, y); nil when it holds none.
function F.nearest(faction, x, y)
    local best, bd = nil, nil
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        local st = r:settlement()
        if not st:is_null_interface() then
            local dx, dy = st:logical_position_x() - x, st:logical_position_y() - y
            local d = dx * dx + dy * dy
            if bd == nil or d < bd then best, bd = r, d end
        end
    end
    return best
end

-- Every good in `region` with stock: pct of it to the taker's settlement nearest (x, y), the
-- taking army's position (plan deviation 3: the settlement may already be null at a raze).
-- `held` (stem -> n) is the battle's reading when the region's pools are gone.
function F.take(region, victim_key, taker, pct, kind, x, y, held)
    if pct <= 0 then return 0 end
    local to = F.nearest(taker, x, y)
    local from = not held and region or nil
    local taken = 0
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local n = F.share(held and held[g.stem] or F.held(region, g.stem), pct)
        if n > 0 then
            F.move(from, to, g.stem, n, kind, victim_key, taker:name())
            taken = taken + n
        end
    end
    return taken
end

-- The owner stock may be taken from, or nil: no region, no owner, a rebel, or the taker itself.
function F.victim(region, taker)
    if not region or region:is_null_interface() or region:is_abandoned() then return nil end
    local v = region:owning_faction()
    if v:is_null_interface() or v:is_rebel() or v:name() == taker:name() then return nil end
    return v
end

-- The raid this character makes: region, victim, taker; nil when it takes from nobody.
function F.raid_target(character)
    if not character:has_military_force() then return nil end
    if character:military_force():active_stance() ~= F.RAIDING then return nil end
    local taker = character:faction()
    local region = character:region()
    local v = F.victim(region, taker)
    if not v then return nil end      -- NO WAR TEST: CA pays raid gold from any owner's land
    if not F.allowed(taker:name(), v:name()) then return nil end
    return region, v, taker
end

function F.on_character_turn_start(character)
    local region, v, taker = F.raid_target(character)
    if not region then return end
    F.take(region, v:name(), taker, F.rates().raid, KIND.raid,
           character:logical_position_x(), character:logical_position_y())
end

-- WHAT F.take WOULD TAKE from `region` at `pct`: {total, parts = {{stem, n}}}, most first, or nil
-- when nothing. Read only - the plates' number, by the same F.share the move uses.
function F.preview(region, pct)
    local parts, total = {}, 0
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local n = F.share(F.held(region, g.stem), pct)
        if n > 0 then
            parts[#parts + 1] = { stem = g.stem, n = n }
            total = total + n
        end
    end
    if total == 0 then return nil end
    table.sort(parts, function(a, b)
        if a.n ~= b.n then return a.n > b.n end
        return a.stem < b.stem
    end)
    return { total = total, parts = parts }
end

-- WHAT THE RAID TAKES NEXT TURN, for the army's plate: F.preview plus `to`, the region key it
-- lands in (nil for a horde). Nothing before the rates are frozen: a UI read must not freeze
-- them on one machine ahead of the turn start that does it everywhere.
function F.raid_preview(character)
    local rates = F.state.rates
    if not rates or (rates.raid or 0) <= 0 then return nil end
    local region, _, taker = F.raid_target(character)
    if not region then return nil end
    local pv = F.preview(region, rates.raid)
    if not pv then return nil end
    local to = F.nearest(taker, character:logical_position_x(), character:logical_position_y())
    pv.to = to and to:name() or nil
    return pv
end

-- WHAT A CAPTURE CHOICE DOES TO `region`'s STORES, for the capture panel: F.preview plus `lost`,
-- true when the taker holds no settlement to carry it to. "sack" and "raze" take their share
-- (nil for the cases F.on_occupation skips: rebels, its own settlement); "occupy" keeps the
-- whole store, which stays with the settlement, rebels' included. nil for any other kind.
function F.capture_preview(region, taker, kind)
    local rates = F.state.rates
    if not rates then return nil end
    local pct
    if kind == "occupy" then
        if region:is_abandoned() or region:owning_faction():name() == taker:name() then return nil end
        local pv = F.preview(region, 100)
        if pv then pv.lost = false end
        return pv
    elseif kind == "sack" or kind == "raze" then
        pct = rates[kind] or 0
    end
    if not pct or pct <= 0 then return nil end
    if not F.victim(region, taker) then return nil end
    local pv = F.preview(region, pct)
    if pv then pv.lost = taker:region_list():num_items() == 0 end
    return pv
end

function F.on_occupation(context)
    local what = F.DECISION[context:occupation_decision_type()]
    if not what then return end
    local character = context:character()
    local taker = character:faction()
    local victim = context:previous_owner()        -- empty for rebels
    if victim == nil or victim == "" or victim == taker:name() then return end
    if not F.allowed(taker:name(), victim) then return end
    local region = context:garrison_residence():region()
    local at_battle = F.at_battle[region:name()]
    F.at_battle[region:name()] = nil
    if F.pool(region, DERPY_MR_FLOWS_GOODS[1].stem) then
        at_battle = nil                            -- live stores win over the battle's reading
    elseif not at_battle then
        F.say("the stores of " .. region:name() .. " could not be read at the " .. what
              .. " - nothing taken")
        return
    end
    F.take(region, victim, taker, F.rates()[what], KIND[what],
           character:logical_position_x(), character:logical_position_y(), at_battle)
end

-- THE STORES AS THEY WERE AT THE BATTLE: the engine drops a razed region's pools before the
-- occupation decision fires (measured 2026-10-02, Venom Glade). CA's Bloodgrounds caches the
-- settlement the same way, on the same event. Not saved: the decision follows in the same session.
F.at_battle = {}
function F.on_battle(context)
    local pb = context:pending_battle()
    if not pb:has_contested_garrison() then return end
    local region = pb:contested_garrison():region()
    local t = {}
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local h = F.held(region, g.stem)
        if h > 0 then t[g.stem] = h end
    end
    F.at_battle[region:name()] = t
end

-- ---- trade --------------------------------------------------------------------------------
function F.capital(faction)
    if faction:has_home_region() then return faction:home_region() end
    local rl = faction:region_list()
    if rl:num_items() > 0 then return rl:item_at(0) end
    return nil
end

-- One pass over the exporter's settlements finds every good's fullest store, so the cost does
-- not grow with the number of partners.
function F.fullest(faction)
    local best = {}
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
            local h = F.held(r, g.stem)
            if h > 0 and (not best[g.stem] or h > best[g.stem].held) then
                best[g.stem] = { region = r, held = h }
            end
        end
    end
    return best
end

function F.lacks(partner, g)
    if F.LACK_TEST == "exists" then return not partner:trade_resource_exists(g.res) end
    local cap = F.capital(partner)
    return cap ~= nil and F.held(cap, g.stem) == 0
end

-- Each faction sends its own exports at its own turn start, so each direction of an agreement
-- runs once a round. A partner with no settlements gets nothing and nothing leaves.
function F.trade(exporter)
    local pct = F.rates().trade
    if pct <= 0 then return end
    local partners = exporter:factions_trading_with()
    if type(partners) == "boolean" then return end   -- measured 2026-10-02 for some faction
    local best = nil
    for i = 0, partners:num_items() - 1 do
        local partner = partners:item_at(i)
        local to = F.capital(partner)
        if to and F.allowed(exporter:name(), partner:name()) then
            best = best or F.fullest(exporter)
            for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
                local b = best[g.stem]
                if b and not F.stopped(exporter:name(), "export", g.stem)
                        and not F.stopped(partner:name(), "import", g.stem) and F.lacks(partner, g) then
                    -- ONLY WHAT FITS LEAVES: trade never destroys stock (spec section 3).
                    -- SURPLUS ONLY, NOT F.share's at-least-1: with it a raided single unit left
                    -- the same turn (measured 2026-10-02) and singles bounced between partners.
                    local n = math.min(math.floor(b.held * pct / 100), F.free(to, g.stem))
                    if n > 0 then
                        F.move(b.region, to, g.stem, n, KIND.trade, exporter:name(), partner:name())
                        b.held = b.held - n
                    end
                end
            end
        end
    end
end

-- ---- the player's trade switches (the Stores panel's Trade tab) ---------------------------
-- Saved in the faction's book as stop[dir][stem] = true; everything allowed by default.
-- Humans only: a computer-run faction has no panel to set them from.
F.DIRS = { export = true, import = true }
F.TAG = "dmr1"
-- in place of a resource's key: every resource one way at once (the panel's four buttons)
F.ALL_STOP, F.ALL_ALLOW = "all_stop", "all_allow"

function F.stopped(fkey, dir, stem)
    local b = F.state.factions[fkey]
    return b ~= nil and b.stop ~= nil and b.stop[dir] ~= nil and b.stop[dir][stem] == true
end

function F.toggle(fkey, dir, stem)
    if not F.DIRS[dir] or not F.is_human(fkey) then return end
    local known = false
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        if g.stem == stem then known = true end
    end
    if not known then return end
    local b = F.book(fkey)
    b.stop = b.stop or {}
    b.stop[dir] = b.stop[dir] or {}
    if F.stopped(fkey, dir, stem) then b.stop[dir][stem] = nil else b.stop[dir][stem] = true end
end

-- `what` is a resource's key (toggle it) or ALL_STOP / ALL_ALLOW (set every one, not a toggle)
function F.apply(fkey, dir, what)
    if what ~= F.ALL_STOP and what ~= F.ALL_ALLOW then return F.toggle(fkey, dir, what) end
    if not F.DIRS[dir] or not F.is_human(fkey) then return end
    local b = F.book(fkey)
    b.stop = b.stop or {}
    b.stop[dir] = {}
    if what == F.ALL_STOP then
        for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do b.stop[dir][g.stem] = true end
    end
end

-- A trade switch: one resource's key, or ALL_STOP / ALL_ALLOW (F.request, below).
function F.send(fkey, dir, stem) return F.request(fkey, dir, stem) end

function F.on_ui_trigger(context)
    local parts = F.parse(context:trigger())
    if not parts then return end
    local cqi = context:faction_cqi()
    for _, k in ipairs(cm:get_human_factions()) do
        local f = cm:get_faction(k)
        if f and not f:is_null_interface() and f:command_queue_index() == cqi then
            F.dispatch(k, parts)
            local S = DERPY_MR_STORES
            if S and S.refresh then pcall(S.refresh) end
            return
        end
    end
end

-- ---- using the stores (spending spec section 2, phase 4) ----------------------------------
-- Every settlement eats provisions at its owner's turn start, and well-stocked stores give a
-- region bundle each: Well fed, Garrison stocked, Comforts (gen_resource_overhaul.USE_BUNDLES).
F.NEED = 2               -- provisions a turn per settlement level
F.FED_TURNS = 5          -- Well fed: this many turns' need still held after eating
F.STOCKED_PCT = 25       -- Garrison stocked and Comforts: this share of one store's space
-- RENEWED EACH TURN, REMOVED THE TURN ITS CONDITION FAILS: 2, not 1, so a bundle cannot lapse
-- before growth is counted, and one the pass no longer reaches (the mod removed) still lapses.
F.BUNDLE_TURNS = 2

-- Daemons, the undead and Beastmen: their buildings make nothing, so they keep nothing to use.
function F.uses_stores(faction)
    local sc = faction:subculture()
    for _, t in ipairs(DERPY_MR_FLOWS_NO_STORES) do
        -- no plain flag: it corrupts the game's string library; the tokens are letters only
        if string.find(sc, "_" .. t .. "_") then return false end
    end
    return true
end

-- One read of a settlement's stores: {stem = held}, and one store's space.
function F.stock(region)
    local held, cap = {}, 0
    local list = region:pooled_resource_manager():resources()
    for i = 0, list:num_items() - 1 do
        local p = list:item_at(i)
        if not p:is_null_interface() then
            local k = p:key()
            if string.sub(k, 1, #F.PREFIX) == F.PREFIX then
                held[string.sub(k, #F.PREFIX + 1)] = p:value()
                if p:maximum_value() > cap then cap = p:maximum_value() end
            end
        end
    end
    return held, cap
end

function F.use_total(held, use)
    local n = 0
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        if g.use == use then n = n + (held[g.stem] or 0) end
    end
    return n
end

-- THE DRAWING RULE (spec section 1): take n from the stores `pick(good)` names, the fullest
-- store first, then the next, until n is taken or they are empty. stocks = {{region, held}};
-- each `held` is updated as it goes. A tie goes by region key, then by resource key, so every
-- machine takes alike. Returns what was taken.
function F.draw_realm(stocks, pick, n, kind, fkey)
    local cands = {}
    for _, s in ipairs(stocks) do
        local rk = s.region:name()
        for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
            if pick(g) and (s.held[g.stem] or 0) > 0 then cands[#cands + 1] = { s = s, stem = g.stem, rk = rk } end
        end
    end
    table.sort(cands, function(a, b)
        local ha, hb = a.s.held[a.stem], b.s.held[b.stem]
        if ha ~= hb then return ha > hb end
        if a.rk ~= b.rk then return a.rk < b.rk end
        return a.stem < b.stem
    end)
    local taken = 0
    for _, c in ipairs(cands) do
        if taken >= n then break end
        local k = math.min(n - taken, c.s.held[c.stem])
        F.move(c.s.region, nil, c.stem, k, kind, fkey, nil)
        c.s.held[c.stem] = c.s.held[c.stem] - k
        taken = taken + k
    end
    return taken
end

-- One settlement's stores of one use.
function F.draw(region, held, use, n, kind, fkey)
    return F.draw_realm({ { region = region, held = held } }, function(g) return g.use == use end, n, kind, fkey)
end

function F.bundle(rkey, region, use, on)
    local b = DERPY_MR_FLOWS_BUNDLES[use]
    if on then
        cm:apply_effect_bundle_to_region(b, rkey, F.BUNDLE_TURNS)
    elseif region:has_effect_bundle(b) then
        cm:remove_effect_bundle_from_region(b, rkey)
    end
end

function F.upkeep_region(region, fkey, uses)
    local fed, war, lux = false, false, false
    if uses then
        local held, cap = F.stock(region)
        local level = 0
        pcall(function() level = region:settlement():primary_slot():building():building_level() end)
        local need = F.NEED * level
        if need > 0 then
            F.draw(region, held, "provisions", need, KIND.eat, fkey)
            fed = F.use_total(held, "provisions") >= F.FED_TURNS * need
        end
        local quarter = cap * F.STOCKED_PCT / 100
        war = cap > 0 and F.use_total(held, "war") >= quarter
        lux = cap > 0 and F.use_total(held, "luxuries") >= quarter
    end
    local rkey = region:name()
    F.bundle(rkey, region, "provisions", fed)
    F.bundle(rkey, region, "war", war)
    F.bundle(rkey, region, "luxuries", lux)
end

function F.upkeep(faction)
    local r = F.rates()
    if not r.upkeep or not (r.ai or faction:is_human()) then return end
    local fkey, uses = faction:name(), F.uses_stores(faction)
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local region = rl:item_at(i)
        if not region:is_null_interface() then F.upkeep_region(region, fkey, uses) end
    end
end

-- ---- the Stores panel's actions (spending spec section 5, phase 7) -------------------------
-- Player only, and only through F.request: in multiplayer every action is a UITrigger.
F.GOOD = {}
for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do F.GOOD[g.stem] = g end
F.SEND_LOSS_PCT = 10
F.ORDER_COST, F.ORDER_TURNS, F.ORDER_COOLDOWN = DERPY_MR_FLOWS_ORDER[1], DERPY_MR_FLOWS_ORDER[2], DERPY_MR_FLOWS_ORDER[3]

function F.stocks(faction)
    local out = {}
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        if not r:is_null_interface() then out[#out + 1] = { region = r, held = (F.stock(r)) } end
    end
    return out
end

function F.owned(faction, rkey)
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        if not r:is_null_interface() and r:name() == rkey then return r end
    end
    return nil
end

function F.lost(n) return math.ceil(n * F.SEND_LOSS_PCT / 100) end

-- SEND HERE: the fullest OTHER store of the resource sends the most whose arrival, after the
-- loss on the road, still fits here. nil when nothing would arrive.
function F.send_plan(faction, rkey, stem)
    if not F.GOOD[stem] then return nil end
    local to = F.owned(faction, rkey)
    if not to then return nil end
    local free = F.free(to, stem)
    if free <= 0 then return nil end
    local from, fh, fk = nil, 0, nil
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local r = rl:item_at(i)
        local k = r:name()
        if not r:is_null_interface() and k ~= rkey then
            local h = F.held(r, stem)
            if h > fh or (h == fh and h > 0 and k < fk) then from, fh, fk = r, h, k end
        end
    end
    if not from then return nil end
    -- an upper bound on what can fit, walked down: arrival is n less a tenth rounded up
    local n = math.min(fh, free + math.ceil(free / 9) + 2)
    while n > 0 and n - F.lost(n) > free do n = n - 1 end
    local got = n - F.lost(n)
    if got <= 0 then return nil end
    return { from = from, to = to, n = n, got = got }
end

function F.send_here(faction, stem, rkey)
    local p = F.send_plan(faction, rkey, stem)
    if not p then return end
    local fkey = faction:name()
    F.move(p.from, nil, stem, p.n, KIND.move, fkey, nil)
    F.move(nil, p.to, stem, p.got, KIND.move, nil, fkey)
end

-- ORDERS: a faction bundle bought with ORDER_COST of one use, drawn realm-wide; then a wait,
-- kept in the faction's book (and so in the save) as the turn it was bought.
function F.order_state(faction, key)
    local o = DERPY_MR_FLOWS_ORDERS[key]
    if not o then return nil end
    local have = 0
    for _, s in ipairs(F.stocks(faction)) do have = have + F.use_total(s.held, o.use) end
    local st = { have = have, cost = F.ORDER_COST, use = o.use }
    local b = F.state.factions[faction:name()]
    local last = b and b.orders and b.orders[key]
    local turn = cm:model():turn_number()
    if last and turn - last < F.ORDER_COOLDOWN then st.wait = last + F.ORDER_COOLDOWN - turn end
    st.ok = st.wait == nil and have >= F.ORDER_COST
    return st
end

function F.order(faction, key)
    local st = F.order_state(faction, key)
    if not (st and st.ok) then return end
    local o, fkey = DERPY_MR_FLOWS_ORDERS[key], faction:name()
    F.draw_realm(F.stocks(faction), function(g) return g.use == o.use end, F.ORDER_COST, KIND.spend, fkey)
    cm:apply_effect_bundle(o.bundle, fkey, F.ORDER_TURNS)
    local b = F.book(fkey)
    b.orders = b.orders or {}
    b.orders[key] = cm:model():turn_number()
end

-- SELL: the Zharr Exchange's price a unit when it is loaded and answers, the fixed rate of the
-- resource's use otherwise. The surplus is what the realm holds above half its space for it.
function F.price(g)
    if type(EX) == "table" and type(EX.sell_price) == "function" then
        local ok, p = pcall(EX.sell_price, g.res)
        if ok and type(p) == "number" and p > 0 then return p end
    end
    return DERPY_MR_FLOWS_SELL_RATE[g.use] or 0
end

function F.sale(faction, stem)
    local g = F.GOOD[stem]
    if not g then return nil end
    local total, space = 0, 0
    local rl = faction:region_list()
    for i = 0, rl:num_items() - 1 do
        local p = F.pool(rl:item_at(i), stem)
        if p then total, space = total + p:value(), space + p:maximum_value() end
    end
    local n = total - math.floor(space / 2)
    if n <= 0 then return nil end
    local price = F.price(g)
    local gold = math.floor(n * price)
    if gold <= 0 then return nil end
    return { n = n, price = price, gold = gold }
end

function F.sell(faction, stem)
    local s = F.sale(faction, stem)
    if not s then return end
    local fkey = faction:name()
    F.draw_realm(F.stocks(faction), function(g) return g.stem == stem end, s.n, KIND.sell, fkey)
    cm:treasury_mod(fkey, s.gold)
end

-- THE ONE DOOR. parts = {action, args...}: a trade switch (export|import, stem), or an action
-- with exactly its own count of parts. Humans only; the actions only with the MCT switch on.
F.ACTIONS = { send = 3, order = 2, sell = 2 }
function F.dispatch(fkey, parts)
    if not F.is_human(fkey) then return end
    local a = parts[1]
    if F.DIRS[a] then
        if #parts == 2 then F.apply(fkey, a, parts[2]) end
        return
    end
    if F.ACTIONS[a] ~= #parts or not F.rates().actions then return end
    local f = cm:get_faction(fkey)
    if a == "send" then F.send_here(f, parts[2], parts[3])
    elseif a == "order" then F.order(f, parts[2])
    else F.sell(f, parts[2]) end
end

-- A CLICK NEVER WRITES THE MODEL ITSELF IN MULTIPLAYER: it goes out as a UITrigger, which CA
-- delivers to every machine in one order, and the listener runs it everywhere at once.
function F.request(fkey, ...)
    local parts = { ... }
    local mp = false
    pcall(function() mp = cm:is_multiplayer() end)
    if not mp then return F.dispatch(fkey, parts) end
    local f = cm:get_faction(fkey)
    if not f or f:is_null_interface() then return end
    CampaignUI.TriggerCampaignScriptEvent(f:command_queue_index(), F.TAG .. "|" .. table.concat(parts, "|"))
end

-- "dmr1|a|b|c" -> {a, b, c}; nil for another mod's id or a part that is not [%w_]+.
function F.parse(id)
    if type(id) ~= "string" or string.sub(id, 1, #F.TAG + 1) ~= F.TAG .. "|" then return nil end
    local parts = {}
    for p in string.gmatch(string.sub(id, #F.TAG + 2), "[^|]+") do
        if not string.match(p, "^[%w_]+$") then return nil end
        parts[#parts + 1] = p
    end
    return parts
end

-- ---- history ------------------------------------------------------------------------------
-- WHOLE NUMBERS ONLY: a fraction crosses CA's table save as "1,1" under a decimal-comma locale.
function F.push(b, turn, totals, made)
    b.turns[#b.turns + 1] = turn
    for _, g in ipairs(DERPY_MR_FLOWS_GOODS) do
        local t = b.total[g.stem] or {}
        b.total[g.stem] = t
        while #t < #b.turns - 1 do t[#t + 1] = 0 end      -- a good added by an update lines up
        t[#t + 1] = math.floor((totals[g.stem] or 0) + 0.5)
    end
    while #b.turns > F.HISTORY do
        table.remove(b.turns, 1)
        for _, t in pairs(b.total) do table.remove(t, 1) end
    end
    b.last = b.now
    for stem, m in pairs(made) do
        b.last[stem] = b.last[stem] or {}
        b.last[stem].made = math.floor(m + 0.5)
    end
    b.now = {}
end

-- At a human faction's turn start, after the engine has filled the stores.
function F.snapshot(faction)
    local S = DERPY_MR_STORES
    if not (S and S.read_realm) then return end
    local totals, made = {}, {}
    for _, s in ipairs(S.read_realm(faction)) do
        for stem, v in pairs(s.held) do totals[stem] = (totals[stem] or 0) + v end
        for stem, v in pairs(s.made) do made[stem] = (made[stem] or 0) + v end
    end
    F.push(F.book(faction:name()), cm:model():turn_number(), totals, made)
end

function F.series(fkey, stem)
    local b = F.state.factions and F.state.factions[fkey]
    if not b then return {}, {} end
    return b.turns, b.total[stem] or {}
end

function F.last(fkey, stem)
    local b = F.state.factions and F.state.factions[fkey]
    return (b and b.last[stem]) or {}
end

function F.on_faction_turn_start(faction)
    F.rates()                                     -- frozen at the first turn start
    if faction:is_human() then
        -- ITS OWN GUARD: the snapshot reads through the UI-side CCO and loc, and a throw there must
        -- not skip the trade below, which is model state every machine has to run alike
        F.guard(F.snapshot, faction)
        F.round_cost, F.cost = F.cost, { raid = 0, turn = 0 }
    end
    -- eat before trading, so a partner is sent what is left; its own guard, so a throw in one
    -- settlement cannot stop the trade every machine must run alike
    F.guard(F.upkeep, faction)
    F.trade(faction)
end

function F.guard(fn, a, slot)
    local t0 = os.clock()
    local ok, e = pcall(fn, a)
    if slot then F.cost[slot] = (F.cost[slot] or 0) + os.clock() - t0 end
    if not ok then F.say(e) end
end

function F.init()
    if F.started then return end
    F.started = true
    core:add_listener("derpy_mr_flows_raid", "CharacterTurnStart", true,
        function(context) F.guard(F.on_character_turn_start, context:character(), "raid") end, true)
    core:add_listener("derpy_mr_flows_occupation", "CharacterPerformsSettlementOccupationDecision", true,
        function(context) F.guard(F.on_occupation, context) end, true)
    core:add_listener("derpy_mr_flows_battle", "CharacterCompletedBattle", true,
        function(context) F.guard(F.on_battle, context) end, true)
    core:add_listener("derpy_mr_flows_ui", "UITrigger", true,
        function(context) F.guard(F.on_ui_trigger, context) end, true)
    core:add_listener("derpy_mr_flows_turn", "FactionTurnStart", true,
        function(context) F.guard(F.on_faction_turn_start, context:faction(), "turn") end, true)
end

cm:add_first_tick_callback(function() F.init() end)

-- FIRST IN CA'S LISTS, NOT APPENDED: cm:saving_game and cm:loading_game call every mod's
-- callback in one unprotected loop, so a mod that throws ahead of this one would stop it and the
-- save would go out without the history (the Zharr Exchange's 2026-10-02 lesson).
local function first(kind, fn)
    local list = cm[kind .. "_game_callbacks"]
    if type(list) == "table" then
        table.insert(list, 1, fn)
    elseif kind == "saving" then
        cm:add_saving_game_callback(fn)
    else
        cm:add_loading_game_callback(fn)
    end
end

first("loading", function(context)
    local ok, t = pcall(function() return cm:load_named_value(F.SAVE, {}, context) end)
    if ok and type(t) == "table" then
        F.state = t
    else
        F.state = {}
        F.say("could not load the stores history: " .. tostring(t))
    end
    F.state.factions = F.state.factions or {}
end)

first("saving", function(context)
    local ok, e = pcall(function() cm:save_named_value(F.SAVE, F.state, context) end)
    if not ok then F.say("could not save the stores history: " .. tostring(e)) end
end)
