-- GENERATED by tools/gen_mr_ui.py - do not edit by hand.
--
-- MCT registration for Resource Overhaul's stores. MCT loads every .lua under
-- script/mct/settings/, so this file only ever runs when MCT is installed. The
-- campaign script freezes these values into the save at the first turn start.

local mct = get_mct and get_mct()
if not mct then return end

local m = mct:register_mod("derpy_more_resources")
m:set_title("Derpy Resource Overhaul")
m:set_author("_D3rpyN3wb_")
m:set_description("How goods move between settlement stores. These are fixed for the life of a campaign: change them from the main menu before starting a new one. In a multiplayer campaign they are ignored and every value is the default on every machine.")
m:add_new_section("stores", "Stores")

local o_raid = m:add_new_option("raid", "slider")
o_raid:set_text("Raid share per turn")
o_raid:set_tooltip_text("Each turn an army raids a settlement, it carries off this share of every resource the settlement keeps, into its own nearest settlement as far as that has room. 0 turns this off.")
o_raid:slider_set_precision(0)
o_raid:slider_set_min_max(0, 50)
o_raid:slider_set_step_size(1, 0)
o_raid:set_default_value(10)
o_raid:set_assigned_section("stores")

local o_sack = m:add_new_option("sack", "slider")
o_sack:set_text("Sack share")
o_sack:set_tooltip_text("Sacking a settlement carries off this share of every resource it keeps, into the sacker's nearest settlement as far as that has room. 0 turns this off.")
o_sack:slider_set_precision(0)
o_sack:slider_set_min_max(0, 100)
o_sack:slider_set_step_size(1, 0)
o_sack:set_default_value(50)
o_sack:set_assigned_section("stores")

local o_raze = m:add_new_option("raze", "slider")
o_raze:set_text("Raze share")
o_raze:set_tooltip_text("Razing a settlement carries off this share of every resource it keeps before it burns. 0 turns this off.")
o_raze:slider_set_precision(0)
o_raze:slider_set_min_max(0, 100)
o_raze:slider_set_step_size(1, 0)
o_raze:set_default_value(50)
o_raze:set_assigned_section("stores")

local o_trade = m:add_new_option("trade", "slider")
o_trade:set_text("Trade share per turn")
o_trade:set_tooltip_text("Each turn, every trade agreement sends this share of a resource from the sender's fullest store to the partner's capital, for each resource the partner lacks. 0 turns this off.")
o_trade:slider_set_precision(0)
o_trade:slider_set_min_max(0, 25)
o_trade:slider_set_step_size(1, 0)
o_trade:set_default_value(5)
o_trade:set_assigned_section("stores")

local o_ai = m:add_new_option("ai", "checkbox")
o_ai:set_text("Resources move between other factions")
o_ai:set_tooltip_text("Raids, sacks and trade between two factions no player controls move resources too. Off: resources move only when a player's faction is one of the two, which makes turns faster on a slow machine.")
o_ai:set_default_value(true)
o_ai:set_assigned_section("stores")
