"""Import the house-ancillary TSVs into a pack through RPFM's MCP server.

    py tools/build_house_ancillaries.py          # writes the ancillary TSVs
    py tools/gen_commission_dilemmas.py          # writes the flow-A rite + dilemma TSVs
    py tools/import_house_ancillaries.py         # creates + fills the pack

Needs RPFM open (its MCP server lives inside it). Talks raw HTTP so the huge decoded-table
responses never have to be read back - import_tsv returns the entire table, which is 290 rows
of JSON for the items fragment.

Re-runnable: the pack is created fresh each time and saved over the same path.
"""
import json
import os
import glob
import sys
import urllib.request

URL = "http://127.0.0.1:45127/mcp"
HDR = {"Content-Type": "application/json",
       "Accept": "application/json, text/event-stream"}
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TSV = os.path.join(ROOT, "Modding Files", "source", "house_ancillaries")
PACK = os.path.join(ROOT, "Modding Files", "Modpacks", "derpy_chd_house_ancillaries.pack")

FRAGS = ["derpy_chd_house_anc_followers", "derpy_chd_house_anc_banners",
         "derpy_chd_house_anc_items"]
SETS = "derpy_chd_house_anc_sets"
# (table, version) - ancillaries_tables is v0 in WH3, NOT the v18 the schema also carries.
DB_TABLES = [("ancillary_info_tables", 0), ("ancillaries_tables", 0),
             ("ancillary_to_effects_tables", 0)]
# only the banners fragment carries these - the assignable magic-standard chain
BANNER_TABLES = [("banners_tables", 1), ("banners_permitted_unit_sets_tables", 0),
                 ("effect_bundles_tables", 4),
                 ("effect_bundles_to_effects_junctions_tables", 3)]
SET_TABLES = [("faction_sets_tables", 0), ("faction_set_items_tables", 1)]

# The 30 custom battle abilities, from tools/gen_custom_abilities.py. Eight tables plus one
# loc, all in a single fragment - see docs/CUSTOM_ABILITIES.md for why each is needed and
# docs/ABILITIES.md for the eight shapes they now come in.
ABIL_FRAG = "derpy_chd_house_anc_abilities"
ABIL_TABLES = [("unit_abilities_tables", 17), ("unit_special_abilities_tables", 74),
               ("special_ability_phases_tables", 44),
               ("special_ability_to_special_ability_phase_junctions_tables", 2),
               ("special_ability_phase_stat_effects_tables", 3),
               # must follow the phases it references
               ("special_ability_phase_attribute_effects_tables", 1),
               ("effects_tables", 0),
               ("effect_bonus_value_unit_ability_junctions_tables", 0)]
ABIL_TSV = os.path.join(ROOT, "Modding Files", "source", "custom_abilities")

# Flow A of the acquisition design: three "Commission a Work" rites, one dilemma each,
# from tools/gen_commission_dilemmas.py. Versions are vanilla's, NOT max(schema) -
# rituals is v4 and dilemmas is v3. Order matters only for readability; RPFM's import_tsv
# does not resolve foreign keys.
COMM_FRAG = "derpy_chd_house_anc_commission"
COMM_TABLES = [("resource_costs_tables", 0),
               ("resource_cost_pooled_resource_junctions_tables", 1),
               ("dilemmas_tables", 3),
               ("cdir_events_dilemma_choice_details_tables", 4),
               # no ritual_payload_* tables: completion_payload points at vanilla's
               # do-nothing record "empty" and the Lua fires the dilemma, because the
               # seven items have to be rolled before the panel can preview them
               ("rituals_tables", 4),
               ("campaign_group_rituals_tables", 1),
               # three text_display records (flow A exhausted, flow B kept/risk). The
               # flow D "bare hook" one is gone: a text_display payload draws NOTHING
               # in the dilemma preview, so the empty vault slot pays materials instead
               ("campaign_payload_ui_details_tables", 2),
               # show_message_event's index resolves through these four - a scripted event
               # with no record behind its index logs the call and draws nothing.
               ("campaign_groups_tables", 0),
               ("campaign_group_members_tables", 1),
               ("campaign_group_member_criteria_values_tables", 0),
               ("event_feed_message_events_tables", 1),
               # The commission cooldown, shortened -1 per tech from two CHD industry
               # nodes. cooldown_mod is the only bonus_value_id in the ritual junction
               # table that reaches a rite's timing at all - there is none for cast_time.
               ("effects_tables", 0),
               ("effect_bonus_value_ritual_junctions_tables", 0),
               ("technology_effects_junction_tables", 0)]

# Loose files carried in the same pack, generated by tools/gen_anc_debug_script.py.
# They ride here rather than in a pack of their own because a new .pack dropped into
# data/ starts DISABLED in the mod manager - it never reaches used_mods.txt, so nothing
# in it loads and the MCT entry never appears. This pack is already enabled.
SCRIPTS = [
    "script/mct/settings/derpy_chd_house_ancillaries.lua",
    "script/campaign/mod/zzz_derpy_chd_anc_debug.lua",
    "script/campaign/mod/zzz_derpy_chd_commission.lua",
    # Three of the four rite icons point straight at CA's own Hell-Forge art in ui2.pack,
    # so they ship nothing. The fourth is ours - see gen_commission_dilemmas.BULL_ICON for
    # why the Tower's bull skull had to be reshaped rather than pointed at.
    "ui/skins/default/derpy_chd_commission/rite_great_furnace.png",
    "ui/skins/default/derpy_chd_commission/ember.png",
    # The binding's event-feed badges. override_icon is a BARE FILENAME resolved against
    # ui/campaign ui/message_icons/ (byte-read out of ui.pack), and every one of vanilla's
    # 18 is generic - none of them is a forge. 74x74, which is what CA's are.
    "ui/campaign ui/message_icons/derpy_chd_binding_good.png",
    "ui/campaign ui/message_icons/derpy_chd_binding_bad.png",
    # Two UI files of OUR OWN, created into CA's rites panel at runtime by the commission
    # Lua. CA's ui/campaign ui/rituals_panel.twui.xml was overridden whole-file for two days
    # and is NOT shipped any more: a whole-file override collides with any other mod that
    # ships the same path and has to be re-merged after every patch that touches the panel.
    # These two carry the same CCO bindings that override carried - both pooled prices on a
    # card, both banks in the header - and the Lua does the rest with Adopt and SetStateText.
    "ui/campaign ui/derpy_chd_rite_costs.twui.xml",
    "ui/campaign ui/derpy_chd_rite_totals.twui.xml",
    "ui/campaign ui/derpy_chd_rite_fire.twui.xml",
]

_sid = None


def _post(payload, headers):
    req = urllib.request.Request(URL, data=json.dumps(payload).encode(),
                                 headers=headers, method="POST")
    with urllib.request.urlopen(req, timeout=300) as r:
        return r.headers, r.read().decode()


def _parse(body):
    for line in body.splitlines():
        if line.startswith("data: ") and line[6:].strip():
            d = json.loads(line[6:])
            if "result" in d:
                return d["result"]
            if "error" in d:
                raise RuntimeError(d["error"])
    raise RuntimeError(f"no result in response: {body[:300]}")


def _session():
    global _sid
    if _sid is None:
        h, _ = _post({"jsonrpc": "2.0", "id": 1, "method": "initialize",
                      "params": {"protocolVersion": "2024-11-05", "capabilities": {},
                                 "clientInfo": {"name": "py", "version": "1"}}}, HDR)
        _sid = h.get("mcp-session-id")
        _post({"jsonrpc": "2.0", "method": "notifications/initialized"},
              {**HDR, "mcp-session-id": _sid})
    return {**HDR, "mcp-session-id": _sid}


def call(tool, args):
    _, body = _post({"jsonrpc": "2.0", "id": 9, "method": "tools/call",
                     "params": {"name": tool, "arguments": args}}, _session())
    res = _parse(body)
    if res.get("isError"):
        raise RuntimeError(f"{tool}: {json.dumps(res)[:400]}")
    return json.loads(res["content"][0]["text"])


def check_keys(plan):
    """Duplicated combined keys, before anything is written.

    THIS RUNS BEFORE EVERY SAVE AND ABORTS ON A FINDING. It shipped twice without it:
    special_ability_to_special_ability_phase_junctions had two rows for arcane_surge and two
    for bound_reprieve on the same (order, ability, self, friends, enemies), and the game
    says nothing at all - the second row is simply not there. Only RPFM's own
    "Duplicated combined keys" ever caught it, on the next manual open of the pack.

    RPFM's MCP diagnostics_check CANNOT be used for this: it short-circuits to
    DependenciesCacheNotGenerated unless the 105MB dependency cache is built, and building it
    takes longer than the MCP session survives. This check needs no cache - a combined key is
    intra-table. The key columns come from the schema (`is_key`), not a hardcoded list, so it
    covers every table this script imports and keeps covering them across schema updates.

    Loc files have no schema definition and are skipped; RPFM checks those itself on import.
    """
    bad = 0
    for entry in plan:
        path, newfile, tsv = entry[:3]
        if "DB" not in newfile:
            continue
        _frag, table, ver = newfile["DB"]
        fields = call("definition_by_table_name_and_version",
                      {"name": table, "version": ver})["Definition"]["fields"]
        keys = [f["name"] for f in fields if f["is_key"]]
        if not keys:
            continue
        full = os.path.join(entry[3] if len(entry) > 3 else TSV, tsv)
        with open(full, encoding="utf-8") as fh:
            cols = fh.readline().rstrip(chr(10)).split(chr(9))
            fh.readline()                                   # the #table;version;path line
            idx = [cols.index(k) for k in keys if k in cols]
            seen = {}
            for n, line in enumerate(fh, 3):
                row = line.rstrip(chr(10)).split(chr(9))
                ck = tuple(row[i] for i in idx)
                if ck in seen:
                    print(f"  DUPLICATE KEY  {table}  line {n} and {seen[ck]}: "
                          + "|".join(ck))
                    bad += 1
                seen[ck] = n
    if bad:
        raise SystemExit(f"{bad} duplicated combined key(s) - nothing written. "
                         "Fix the generator, not the TSV.")


def check_lua():
    """Refuse to pack Lua that reads an ALL_CAPS name nothing ever declares.

    Flow B shipped completely dead this way: BINDING and BINDING_RITE were Python
    constants in gen_commission_dilemmas.py, used to build the DB rows but never
    interpolated into the Lua template. An undeclared Lua global is nil, not an error,
    so every branch comparing against them was unreachable - and luac -p, check_lua_api.py
    and the game all reported nothing at all. Only a live campaign found it.

    Use the checker's own main(), not undeclared() per file: a pack global legitimately
    crosses files (the Exchange's generated EX_PRODUCTION, the Guilds' GUILDS) and the
    isolated call reports every one of them, which is the bypass its docstring warns about.
    """
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import check_lua_undeclared
    pat = os.path.join(ROOT, "Modding Files", "pack", "script", "campaign", "mod", "*.lua")
    if check_lua_undeclared.main(sorted(glob.glob(pat))):
        raise SystemExit("Lua reads names nothing declares - nothing written.")


def main():
    check_lua()
    call("set_game_selected", {"game_name": "warhammer_3", "rebuild_dependencies": False})
    plan = []
    for frag in FRAGS:
        tables = DB_TABLES + (BANNER_TABLES if frag.endswith("banners") else [])
        for table, ver in tables:
            plan.append((f"db/{table}/{frag}", {"DB": [frag, table, ver]},
                         f"{table}__{frag}.tsv"))
        plan.append((f"text/db/{frag}.loc", {"Loc": frag}, f"loc__{frag}.tsv"))
    for table, ver in SET_TABLES:
        plan.append((f"db/{table}/{SETS}", {"DB": [SETS, table, ver]},
                     f"{table}__{SETS}.tsv"))
    for table, ver in ABIL_TABLES:
        plan.append((f"db/{table}/{ABIL_FRAG}", {"DB": [ABIL_FRAG, table, ver]},
                     f"{table}__{ABIL_FRAG}.tsv", ABIL_TSV))
    plan.append((f"text/db/{ABIL_FRAG}.loc", {"Loc": ABIL_FRAG},
                 f"loc__{ABIL_FRAG}.tsv", ABIL_TSV))
    for table, ver in COMM_TABLES:
        plan.append((f"db/{table}/{COMM_FRAG}", {"DB": [COMM_FRAG, table, ver]},
                     f"{table}__{COMM_FRAG}.tsv"))
    plan.append((f"text/db/{COMM_FRAG}.loc", {"Loc": COMM_FRAG},
                 f"loc__{COMM_FRAG}.tsv"))

    for entry in plan:
        full = os.path.join(entry[3] if len(entry) > 3 else TSV, entry[2])
        if not os.path.isfile(full):
            raise SystemExit(f"missing {full} - run build_house_ancillaries.py first")

    check_keys(plan)

    pack = call("new_pack", {})["String"]
    print(f"new pack: {pack}")

    for entry in plan:
        path, newfile, tsv = entry[:3]
        full = os.path.join(entry[3] if len(entry) > 3 else TSV, tsv)
        call("new_packed_file", {"pack_key": pack, "path": path,
                                 "new_file": json.dumps(newfile)})
        call("import_tsv", {"pack_key": pack, "table_path": path, "tsv_path": full})
        rows = sum(1 for _ in open(full, encoding="utf-8")) - 2
        print(f"  {rows:5d}  {path}")

    for rel in SCRIPTS:
        src = os.path.join(ROOT, "Modding Files", "pack", *rel.split("/"))
        if not os.path.isfile(src):
            raise SystemExit(f"missing {src} - run its generator in tools/ first")
        call("add_packed_files", {"pack_key": pack, "source_paths": [src],
                                  "destination_paths": json.dumps([{"File": rel}])})
        print(f"  {os.path.getsize(src):5d}B  {rel}")

    call("save_pack_as", {"pack_key": pack, "path": PACK})
    print(f"\nsaved {PACK}")
    # plan holds only the DB/loc imports; the loose script files are added separately
    print(f"  {len(plan) + len(SCRIPTS)} files")


if __name__ == "__main__":
    try:
        main()
    except urllib.error.URLError:
        sys.exit("RPFM is not running - its MCP server only exists while RPFM is open")
